openapi: 3.0.1
info:
  title: rag-backend-api
  version: 1.0.0

paths:
  /ragQuery:
    post:
      summary: Enterprise RAG Query API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                businessContext:
                  type: string
              required:
                - question
      responses:
        '200':
          description: RAG answer with citations
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                  citations:
                    type: array
                  rawDocuments:
                    type: array
